### ISSUE TITLE
Fill "Community Standards" checklist

### ISSUE THREAD

**Issue by GodHermit** [GodHermit/survival-manual#35]
- [ ] Update `README.md`
- [ ] Add code of conduct
- [ ] Choose licence
- [ ] Set up a security police
- [ ] Create issue templates
